Performance fw schedular changes
sushanthakumar/dolphin pull request #7
Opened 2021-03-13 10:40 UTC by sushanthakumar

**What this PR does / why we need it**:
This PR includes scheduler changes for performance framework
Note:
Failed task handling changes will be updated as part of new PR
Resource delete is currently not handled
Unit test scripts to be added as new commit

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2021-03-13 11:24 UTC, NajmudheenCT commented on delfin/drivers/dell_emc/vmax/vmax.py
> +        """Collect array performance metrics"""
should we open an issue to update vmax collection according to new signature?

2021-03-13 11:24 UTC, NajmudheenCT commented on delfin/common/constants.py
> +    PERIODIC_TASK_SCHEDULE_INTERVAL = 180
I hope it is better to put in delfin.conf.. user customizable

2021-03-13 11:24 UTC, NajmudheenCT commented on delfin/drivers/dell_emc/unity/unity.py
> +    def collect_perf_metrics(self, context, storage_id,
No need to add for this empty  implementation for unity now.

2021-03-13 11:24 UTC, NajmudheenCT commented on delfin/drivers/driver.py
> +    @abc.abstractmethod
IMO make it non_abstract.. not a mandatory method to implement

2021-03-13 11:24 UTC, NajmudheenCT commented on delfin/tests/unit/drivers/dell_emc/vmax/test_vmax.py
> -    @mock.patch.object(VMaxRest, 'post_request')
No need to remove the test.. we may need to change the test according to new signature..

2021-03-13 11:24 UTC, NajmudheenCT commented on etc/delfin/delfin.conf
> +performance_collection_interval = 300
Add all other configs here, retry_count, schedule_check intervel etc..

2021-03-16 12:02 UTC, sushanthakumar commented on delfin/drivers/dell_emc/vmax/vmax.py
> +        """Collect array performance metrics"""
Updated the signature currently

2021-03-16 12:02 UTC, sushanthakumar commented on delfin/common/constants.py
> +    PERIODIC_TASK_SCHEDULE_INTERVAL = 180
done

2021-03-16 12:02 UTC, sushanthakumar commented on delfin/drivers/dell_emc/unity/unity.py
> +    def collect_perf_metrics(self, context, storage_id,
done

2021-03-16 12:03 UTC, sushanthakumar commented on delfin/drivers/driver.py
> +    @abc.abstractmethod
done

2021-03-16 12:03 UTC, sushanthakumar commented on delfin/tests/unit/drivers/dell_emc/vmax/test_vmax.py
> -    @mock.patch.object(VMaxRest, 'post_request')
done

2021-03-16 12:03 UTC, sushanthakumar commented on etc/delfin/delfin.conf
> +performance_collection_interval = 300
done

2021-03-16 12:59 UTC, NajmudheenCT commented on delfin/drivers/dell_emc/vmax/vmax.py
> +        interval = (end_time - start_time) / 1000
This may not be correct, in the client we use current_time -interval to set start_time , we should pass star_time and end_time to client ..

2021-03-16 12:59 UTC, NajmudheenCT commented on delfin/task_manager/tasks/telemetry.py
> +                    'failed task scheduling'),
failed task or just task?

2021-03-16 13:54 UTC, AmitRoushan requested changes

2021-03-16 13:54 UTC, AmitRoushan commented on delfin/drivers/api.py
>          """Collect array performance metrics"""
DOCString can be improved

2021-03-16 13:54 UTC, AmitRoushan commented on delfin/drivers/fake_storage/__init__.py
> +    def collect_perf_metrics(self, context, storage_id,
IMO, The responses from the collect metric should get modified as per latest resource and metric name

2021-03-16 13:54 UTC, AmitRoushan commented on delfin/task_manager/tasks/telemetry.py
> +                db.failed_task_delete(ctxt, failed_task['id'])
IMO the DB operation can be optimized with ```Delete from <table_name>```

2021-03-16 13:54 UTC, AmitRoushan commented on delfin/task_manager/tasks/telemetry.py
> +                db.task_update(ctxt, task['id'], {'last_run_time': None})
DB query can be optimized

2021-03-16 13:54 UTC, AmitRoushan commented on delfin/task_manager/tasks/telemetry.py
> +                last_run_time = current_time
```last_run_time``` redundant variable. IMHO, ```current_time``` can be used

2021-03-19 02:44 UTC, closed without merging